version: "3.8"

services:
  web:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8080
    volumes:
      - ./app:/usr/src/app
    ports:
      - "8080:8080"

    env_file:
      - ./.env


  db:
    image: postgres:17
    container_name: crm_postgres
    env_file:
      - ./.env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:
