version: '3.8'

services:
  web:
    build: ./app
    working_dir: /app
    container_name: django_crm
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy
    command: ["waitress-serve", "--host=0.0.0.0", "--port=8000", "app.config.wsgi:application"]

  db:
    image: postgres:17
    container_name: crm_postgres
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "crm_user"]
      interval: 10s
      retries: 5
      timeout: 5s

volumes:
  postgres_data:
